{% set version = "1.1.0" %}

package:
  name: tf_slim
  version: {{ version }}.post20231128
source:
  url: https://github.com/google-research/tf-slim/archive/refs/heads/r{{ version }}.zip
  sha256: f9f6f04c9852bd6bc76bc11e1090ae44ff1dea31a5d7ef4f5feeaa20ae55cdb2
  patches:
    # Find the commit after the latest release 1.1.0
    # https://github.com/google-research/tf-slim/pull/21
    # git checkout remove_layer_apply
    # git format-patch 8f0215e924996d7287392241bc8d8b1133d0c5ca
    - 0001-Internal-change.patch
    - 0002-Set-the-default-value-for-the-use_gpu-param-to-True-.patch
    - 0003-Fix-a-NaN-issue-with-streaming_covariance.patch
    - 0004-Remove-the-private-TF-API-usage-of-layers.patch
    - 0005-Internal-Google-change.patch
    - 0006-Fix-TensorFlow-checkpoint-and-trackable-imports.patch
    - 0007-NumPy-Fix-NumPy-1.23-compatibility-problems-in-tf_sl.patch
    - 0008-Fix-tests-broken-by-previous-change-list-due-to-smal.patch
    - 0009-NumPy-Remove-references-to-deprecated-NumPy-type-ali.patch
    - 0010-NumPy-Remove-references-to-deprecated-NumPy-type-ali.patch
    - 0011-Remove-legacy-references-from-ops.py.patch
    - 0012-Redirect-references-to-stack-and-unstack-to-their-ne.patch
    - 0013-Refactor-case-and-case_v2-out-of-control_flow_ops.py.patch
    - 0014-Move-control_flow_ops.Assert-into-its-own-file-contr.patch
    - 0015-Move-control_flow_ops.while_loop-into-its-own-file-w.patch
    - 0016-Redirect-references-from-control_flow_ops.cond-to-co.patch
    - 0017-Update-some-isinstance-checks-of-tf.compat.v1.Variab.patch
    - 0018-Update-references-from-variables.VariableV1-to-its-n.patch
    - 0019-Update-references-from-tensorflow.python.platform-to.patch
    - 0020-Update-legacy-reference-to-variable_scope.variable-i.patch
    - 0021-Internal-Code-Change.patch
    - 0022-Delete-remnants-of-toollog-removal.patch
    - 0023-NumPy-Fix-uses-of-functions-deprecated-in-NumPy-1.25.patch
    - 0024-Use-ExitStack-and-call-ops.device-device-only-when-d.patch
    - 0025-Fix-streaming_concat-crashes-on-specific-and-relativ.patch
    - 0026-Update-ops.Tensor-references-to-third_party-tensorfl.patch
    - 0027-Update-legacy-references-to-tensor.Tensor.patch
    - 0028-Move-references-to-TF-resource-variable-toggle-funct.patch
    - 0029-Update-outdated-references-to-functions-imported-by-.patch
    # https://github.com/google-research/tf-slim/pull/21
    - 0030-Remove-call-to-layer.apply-and-just-use-__call__.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - tensorflow >=2
  run_constrained:
    - keras <3.0a

test:
  imports:
    - tf_slim

about:
  home: https://github.com/Maxar-Corp/ratpac/tree/tf_slim/TF-slim
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'TF-Slim: A framework for flexible Reinforcement Learning research'
  description: |
    TF-slim is a new lightweight high-level API of TensorFlow
    for defining, training and evaluating complex models. This
    directory contains code for training and evaluating several
    widely used Convolutional Neural Network (CNN) image
    classification models using TF-slim.


extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - hmaarrfk
