{% set version = "1.1.0" %}

package:
  name: tf_slim
  version: {{ version }}
source:
  url: https://github.com/google-research/tf-slim/archive/refs/heads/r{{ version }}.zip
  sha256: f9f6f04c9852bd6bc76bc11e1090ae44ff1dea31a5d7ef4f5feeaa20ae55cdb2
  patches:
    # https://github.com/google-research/tf-slim/pull/21
    - 21-avoid_layer_apply.patch
    # https://github.com/google-research/tf-slim/commit/550196c9db2b76d9e23bc394f4dd02df78159a6a
    - numpy_123_comaptibility.patch

build:
  noarch: python
  number: 3
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - tensorflow >=2
  run_constrained:
    - keras <3.0a

test:
  imports:
    - tf_slim

about:
  home: https://github.com/Maxar-Corp/ratpac/tree/tf_slim/TF-slim
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'TF-Slim: A framework for flexible Reinforcement Learning research'
  description: |
    TF-slim is a new lightweight high-level API of TensorFlow
    for defining, training and evaluating complex models. This
    directory contains code for training and evaluating several
    widely used Convolutional Neural Network (CNN) image
    classification models using TF-slim.


extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - hmaarrfk
